tmax-cloud/argocd-installer

- application/yaml/otcontainerkit-operator.yaml
- manifest/otcontainerkit-operator/namespace.yaml
- manifest/otcontainerkit-operator/otcontainerkit-operator.jsonnet
- manifest/otcontainerkit-operator/redis-cluster-crd.yaml
- manifest/otcontainerkit-operator/redis-standalone-crd.yaml
- manifest/otcontainerkit-operator/role-binding.yaml
- manifest/otcontainerkit-operator/role.yaml
- manifest/otcontainerkit-operator/serviceaccount.yaml
argoCD를 이용, ot-container-kit의 redis-operator 설치 위한 manifests작성
1. application/yaml/경로에 argoCD server가 인식할 수 있도록 yaml file 추가
2. manifest/otcontainerkit-operator생성
3. manifest/otcontainerkit-operator 하위 필요 k8s resource manifest file들 추가
> Add ot-container-kit redis-operator install manifests

- .gitignore
- manifest/hyperauth/initialization.yaml
Hyperregistry client의 redirect uri가 잘못 하드코딩 되어있던 부분을 "*"로 변경
> HyperAuth configmap 수정

- manifest/hypercloud/webhook-configuration.yaml
hypercloud-mutator 웹훅 설정에서
자기 자신인 hypercloud-api-server와 postgres는 예외처리 하도록 변경
> hypercloud-api-server와 postgres 웹훅 예외처리

- manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.jsonnet
strimzi kafka operator의 emptyDir sizeLimit 1Mi → 50Mi로 상향
> strimzi kafka operator의 emptyDir sizeLimit 50Mi로 상향

- manifest/api-gateway/cert-manager/cert-manager-values.yaml
- manifest/api-gateway/cert-manager/values.yaml
IMS 286331 
cert-manager에 아래 arg 추가
--enable-certificate-owner-ref=true
이유: certificate 삭제 시 certificate에서 생성한 secret도 같이 삭제되게 하기 위해서 추가 
상세내용: 
secret의 ownerReferences를 추가하여 cert-manager controller에서 삭제 하게끔 함
> [IMS] 286331  certificate삭제 해당 secret 같이 삭제

- application/helm/templates/otcontainerkit-operator.yaml
- manifest/otcontainerkit-redis-operator/otcontainerkit-operator.jsonnet
1. helm/templates 하위 redis module에 time_zone 변수 추가
2. manifest 하위 redis module에 time_zone 값이 "UTC" 가 아닌 경우 volumeMounts, volume객체가 추가되도록 jsonnet수정
> Add timezone redis-operator

- application/helm/templates/hypercloud.yaml
global에서 domain 변수를 설정해주어도 hypercloud 모듈의 jsonnet에 반영이 되지않던 현상을 수정했습니다.
> [mod] hypercloud jsonnet에 global.domain 변수 사용하도록 수정

- application/helm/templates/hyperregistry.yaml
- manifest/hyperregistry/templates/core/core-cm.yaml
- manifest/hyperregistry/templates/core/core-dpl.yaml
- manifest/hyperregistry/values.yaml
* hyperregistry가 argocd-installer로 설치되는 상에서 oidc연동이 되도록 변경
1. helm/templates/hyperregistry.yaml에 oidc 관련해 내려주는 변수(client-id, client-secret, auth-url, group-name) 추가
2. manifest/hyperregistry helm chart에 oidc 변수 추가 및 커스터마이징
- master cluster
1. client id: hyperregistry
3. group name: hypercloud5
- single cluster
1. client id: ((cluster ns))-((cluster name))-hyperregistry
2. group name: ((cluster-ns))-((cluster name))-hyperregistry
> [hyperregistry] IMS#289299 - feat: enable hyperregistry oidc 

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/hypercloud.yaml
- manifest/hypercloud/hypercloud-api-server.jsonnet
- manifest/hypercloud/hypercloud-multi-operator.jsonnet
- manifest/hypercloud/hypercloud-single-operator.jsonnet
- manifest/hypercloud/timescaledb.jsonnet
[add] hypercloud-api-server kubectl CLI 기능을 위한 KUBECTL_TIMEOUT 환경변수 추가
[IMS 291634](https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?issueId=291634&menuCode=issue_search) 참고
> [add] hypercloud-api-server kubectl CLI 기능을 위한 KUBECTL_TIMEOUT 환경변수 추가

- manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.yaml
KafkaMirromaker2 spec.clusters의 값이 없으면 콘솔 상에서 페이지가 깨지는 오류 발생
spec.clusters는 필수 값이기 때문에 CRD 변경하여 required 항목으로 추가하여 조치
> [ims][293381] kafka 관련 CRD 필수 스펙 변경

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/template-service-broker.yaml
- manifest/template-service-broker/tsb-deployment.jsonnet
- application/helm/master-values.yaml에 logLevel 변수 추가
- application/helm/single-values.yaml에 logLevel 변수 추가
- application/helm/templates/template-service-broker.yaml에 내려주는 변수 추가
- manifest/tsb-deployment.jsonnet에서 버전 수정 및 --zap-log-level args 추가
- template-operator 버전: v0.2.6 -> v0.2.8로 수정 
- cluster_tsb 버전: v0.1.3 -> v0.1.6로 수정 
- tsb 버전: v0.1.3 -> v0.1.6로 수정
> [template-service-broker] Loglevel 설정

- manifest/cicd-operator/cicd-operator.jsonnet
- manifest/gitea/charts/memcached/values.yaml
- manifest/gitea/charts/postgresql/values.yaml
- manifest/gitea/values.yaml
- manifest/nexus/values.yaml
- manifest/sonarqube/templates/sonarqube.yaml
- manifest/tekton-pipeline/tekton-pipeline.jsonnet
- manifest/tekton-trigger/tekton-trigger.jsonnet
(requests cpu/requests memory/limits cpu/limits memory)
[tekton-pipelines]
tekton-pipelines-controller (100m/100Mi/500m/500Mi)
tekton-pipelines-webhook (100m/100Mi/500m/500Mi)
[tekton-trigger]
tekton-triggers-controller (100m/100Mi/500m/500Mi)
tekton-triggers-core-interceptors (100m/100Mi/500m/500Mi)
tekton-triggers-webhook (100m/100Mi/500m/500Mi)
[cicd-operator]
blocker (100m/100Mi/500m/500Mi)
cicd-operator (100m/100Mi/500m/500Mi)
[gitea]
gitea (100m/128Mi/100m/128Mi)
gitea-memcached (250m/256Mi/250m/256Mi)
gitea-postgresql (250m/256Mi/250m/256Mi)
[sonarqube]
sonarqube (2/4.5Gi/1/4Gi)
[nexus]
nexus3 (4/8Gi/4/8Gi)
> [chore] add resources - tekton, cicd-operator, gitea, sonarqube, nexus

- manifest/api-gateway/gateway/values.yaml
- aws 환경에 gateway 생성시 사용하는 nlb를 public nlb로 변경했습니다.
> gateway nlb 생성 방식(private=> public)수정

- application/helm/templates/istio-1-15-4.yaml
- manifest/istio/istio-gateway/templates/job.yaml
- manifest/istio/istio-gateway/values.schema.json
- manifest/istio/istio-gateway/values.yaml
kubectl 이미지에 폐쇄망 사용가능하게 적용 
변경사항 
- application/helm/templates/istio-1-15-4.yaml 에 parameters 추가 
- manifest/istio/istio-gateway/templates/job.yaml 에 privateRegistry 값 여부에 따라 private 이미지 주소 사용 결정 
- manifest/istio/istio-gateway/values.yaml 에 job.privateRegistry flag 추가 및 values.schema.json에 schema 추가
> feat : Update job.privateRegistry for enable to use private registry

- manifest/hypercloud/hypercloud-single-operator.yaml
* hyercloud-single-operator 변경점
* CRD 버전 v1beta1 → v1으로 업그레이드
* 그에따라 **콘솔에서도 한글화를 위해 v1 key mapping 정보로 업데이트 필요**, 해당 정보는 [링크](https://github.com/tmax-cloud/install-hypercloud/blob/5.1/hypercloud-single-operator/key-mapping/hypercloud-single-operator-crd-v5.1.1.0-v1.xls)에 업로드
* hypercloud-api-server는 변경점 없음
> [feat] k8s 1.25버전 호환을 위한 hypercloud-single-operator CRD v1 업그레이드

- manifest/argocd/templates/ingress.yaml
- Modify argocd ingress service port
- binding to 443 port cause "bad gateway" when we use to tradefik. (ingress-nginx is fine)
- origin: port binding to 443(https)
- new: port binding to 80(http)
> Update argocd ingress port binding

- manifest/api-gateway/oauth2-proxy/templates/_helpers.tpl
oauth2proxy에서 500 internal 에러 문제
해결: full domain 네임으로 설정
> fix : redis db의 domain 네임에 cluster.local 추가 (ims 298144 관련)

- manifest/api-gateway/oauth2-proxy/Chart.yaml
- manifest/api-gateway/oauth2-proxy/values.yaml
[ims][[300246](https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?issueId=300246&menuCode=issue_list)] email이 없는 경우에도 로그인이 가능하도록 수정
* oauth2-proxy를 수정하여 email이 없는 경우에 email을 "" 처리하여 로그인 가능하도록 수정
> [ims][300246] email이 없는 경우에도 로그인이 가능하도록 수정

- manifest/opensearch/opensearch-fluentd.jsonnet
argocd-installer main 브랜치 opensearch 설치 시 opensearch-log4j2-config 생성 오류에 따른 오탈자 수정
> [mod] opensearch-log4j2-config 오탈자 수정

- manifest/image-validating-webhook/image-validating-webhook.jsonnet
- manifest/image-validating-webhook/image-validating-webhook.yaml
hc-5.2 릴리즈에 추가: image-validating-webhook v5.0.6 (코사인 서명 검사 기능 도입)
> [image-validating-webhook] version up to 5.0.6 in hc-5.2

- manifest/argorollout/templates/deployment.yaml
- manifest/argorollout/templates/namespace.yaml
- manifest/argorollout/templates/secret.yaml
- manifest/argorollout/templates/service.yaml
- manifest/argorollout/templates/serviceaccounts.yaml
> [argo-rollouts] fix: 누락된 namespace 추가 to hc-5.2

- manifest/argorollout/templates/ingress.yaml
- manifest/argorollout/templates/service.yaml
> [argo-rollout] mod: change traefik ingress to http port in hc-5.2

- manifest/hyperregistry/templates/database/database-ss.yaml
- manifest/hyperregistry/templates/redis/statefulset.yaml
- manifest/hyperregistry/templates/trivy/trivy-sts.yaml
hyperregistry에서 sts로 생성되는 3개의 서브모듈(trivy, database, redis)에 대해  
argocd sync시 timezone not found 에러가 발생하지 않도록 timezone UTC or Else로 모두 적용될 수 있도록 변경
> [hyperregistry] fix: statefulset timezone config in hc-5.2

- manifest/argorollout/templates/service.yaml
> [argo-rollouts] hotfix: missing service name

- manifest/argocd/templates/statefulset.yaml
- manifest/argorollout/templates/ingress.yaml
1. 콘솔 연동을 위해 콘솔과 argo-rollout manifest 간 ingress label 동기화 - rollout
2. argocd-application-controller의 메모리 부족으로 인해 자주 죽어버리는 현상 해결을 위해 default resource를 2배 상향
> [argocd, argo-rollouts] 두가지 수정 사항 적용 in hc-5.2

- manifest/loki/loki-config.jsonnet
loki config: 사용하지 않는 ruler 기능에서 발생한 permission 오류 해결을 위해 ruler 설정 삭제
> [mod] loki ruler permission error 수정
