- manifest/service-mesh/jaeger/7.jaeger.jsonnet
fix jaeger version from 1.19 -> 1.9
> fix jaeger version

- manifest/efk/efk.jsonnet
싱글 클러스터 일 때, kibana base_url 설정 및 gatekeeper base-uri 설정 적용
> Kibana-gatekeeper cluster_name 조건 설정

- manifest/hyperauth/hyperauth.jsonnet
- manifest/hyperauth/kafka.jsonnet
> jsonnet error fix

- application/app_of_apps/single-applications.yaml
> application.yaml error fix

- application/app_of_apps/single-applications.yaml
- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/hyperregistry.yaml
- application/helm/templates/opensearch.yaml
- manifest/opensearch/opensearch-fluentd.jsonnet
- manifest/opensearch/opensearch-ingress.jsonnet
- manifest/opensearch/opensearch-securityconfig.jsonnet
hyperregistry application 추가, opensearch 에러 수정
> hyperregistry application 추가, opensearch 에러 수정

- application/helm/templates/jaeger.yaml
> jaeger error fix

- manifest/opensearch/opensearch-fluentd.jsonnet
> opensearch error fix

- manifest/opensearch/opensearch-fluentd.jsonnet
settings.sh 실행을 위한 securityContext 변경
> dashboards securityContext 설정 변경

- manifest/opensearch/opensearch-fluentd.jsonnet
- manifest/opensearch/opensearch-securityconfig.jsonnet
settings.sh (index policy 생성 sh)실행 이후 root user 에러 수정
> [mod] dashboard command 수정

- manifest/opensearch/opensearch-fluentd.jsonnet
- manifest/opensearch/opensearch-service.yaml
fluentd plugin 설정 관련 누락된 내용 추가
opensearch jsonnet 일부 수정
> fluentd opensearch plugin 설정

- manifest/opensearch/opensearch-fluentd.jsonnet
config 파일 이름 및 수정된 config 내 오류 수정
> opensearch dashboard config 수정

- manifest/opensearch/opensearch-dashboards-index-policy.yaml
- manifest/opensearch/opensearch-fluentd.jsonnet
- manifest/opensearch/opensearch-securityconfig.jsonnet
1. hyperauth-ca 마운트 삭제
2. opensearch securityconfig ca-path 설정 삭제
3. 오픈서치 팟 전체 동시에 띄울 경우에 발생하는 대시보드 error 수정
> Opensearch hyperauth 공인인증서 설정 수정

- application/helm/master-values.yaml
- application/helm/templates/hyperregistry.yaml
Hyperregistry 마스터 클러스터에는 설치되지 않도록 변경
> Hyperregistry 마스터 클러스터에는 설치되지 않도록 변경

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/jsonnet/params.libsonnet
- application/yaml/opensearch.yaml
- manifest/opensearch/README.md
- manifest/opensearch/opensearch-fluentd.jsonnet
- manifest/opensearch/opensearch-ingress.jsonnet
- manifest/opensearch/opensearch-securityconfig.jsonnet
fluentd 이미지 변경 적용에 따른 manifest 및 application file 수정
> opensearch fluentd plugin 적용을 위한 이미지 변경

- .gitignore
- application/helm/master-values.yaml
capi enabled default값을 false 에서 true로 변경
> capi enabled default값 변경

- application/helm/master-values.yaml
capi enabled default값을 false에서 true로 변경
> [capi] enabled default값 true로 변경

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/hyperauth.yaml
- application/helm/templates/hypercloud.yaml
- application/helm/templates/opensearch.yaml
- manifest/hyperauth/hyperauth.jsonnet
- manifest/hyperauth/initialization.yaml
- manifest/hypercloud/hypercloud-api-server.jsonnet
- manifest/hypercloud/hypercloud-multi-operator.jsonnet
- manifest/hypercloud/hypercloud-single-operator.jsonnet
- manifest/hypercloud/postgres.jsonnet
- manifest/opensearch/opensearch-fluentd.jsonnet
- manifest/opensearch/opensearch-ingress.jsonnet
- manifest/opensearch/opensearch-securityconfig.jsonnet
> [postgres] storage class 변수화

- application/helm/master-values.yaml
- manifest/hyperauth/hyperauth.jsonnet
- manifest/hyperauth/initialization.yaml
> hyperauth pvc 오류 수정

- manifest/hypercloud/hypercloud-multi-operator.jsonnet
capi-template 수정
1. audit 관련 config 제거
2. hyperauth 인증서 관련 설정 제거
> [hypercloud] capi-template 수정

- manifest/hypercloud/hypercloud-multi-operator.jsonnet
> [hypercloud] capi template 수정

- manifest/hypercloud/hypercloud-multi-operator.jsonnet
[ims][285253] calico version을 install-cni 기준으로 fix될 수 있도록 cluster template변경
> [hypercloud] multi-operator cluster template manifest

- manifest/hyperregistry/templates/database/database-ss.yaml
- manifest/hyperregistry/templates/notary/notary-signer.yaml
- manifest/hyperregistry/templates/redis/statefulset.yaml
> [fix] hyperregistry offline env vars2 

- manifest/prometheus/node-exporter-serviceMonitor.yaml
prometheus node-exporter servicemonitor relabel
> [fix] prometheus node-exporter servicemonitor

- manifest/hyperauth/initialization.yaml
opensearch client role 추가
export json과 diff비교 용이하도록 config 순서 조정
> [hyperauth] opensearch client role 추가

- manifest/api-gateway/console/Chart.yaml
- manifest/api-gateway/console/console-values.yaml
> [console] version update

- application/helm/templates/strimzi-kfka-operator.yaml
- manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.jsonnet
kafka 모듈 TimeZone 설정 추가
관련 IMS[[282982](https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?issueId=282982&menuCode=issue_search)]
> [kafka] TimeZone 설정 추가

- application/helm/templates/hyperauth.yaml
- manifest/hyperauth/hyperauth.jsonnet
- manifest/hyperauth/initialization.yaml
1. timeZone 설정 추가
2. serviceAccount 설정 변경
- serviceAccount secret token volume mount
- clusterrole 권한 변경 (pod, list)
> [hyperauth] timeZone 설정 추가, serviceAccount 설정 변경

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/api-gateway-bootstrap.yaml
- application/helm/templates/argocd.yaml
- application/helm/templates/gitlab.yaml
- form/jsonnet-example.jsonnet
- manifest/api-gateway-bootstrap/templates/namespaces.yaml
- manifest/api-gateway/console/templates/deployment.yaml
- manifest/efk/efk.jsonnet
- manifest/gitlab/templates/deployment.yaml
- manifest/grafana/grafana.jsonnet
- manifest/hyperauth/hyperauth.jsonnet
- manifest/hyperauth/kafka.jsonnet
- manifest/hypercloud/hypercloud-api-server.jsonnet
- manifest/hypercloud/hypercloud-multi-operator.jsonnet
- manifest/hypercloud/postgres.jsonnet
- manifest/hyperregistry/values.yaml
- manifest/opensearch/opensearch-fluentd.jsonnet
- manifest/prometheus/prometheus.jsonnet
- manifest/service-mesh/istio/5.istio-deploy.jsonnet
- manifest/service-mesh/istio/5.istio-sidecar-configmap.jsonnet
- manifest/service-mesh/jaeger/7.jaeger.jsonnet
- manifest/service-mesh/kiali/8.kilai.jsonnet
- manifest/tekton-pipeline/tekton-pipeline.jsonnet
- manifest/tekton-trigger/tekton-trigger.jsonnet
현재까지 올라온 time zone pr merge후 에러 수정
아직 timezone이 미반영된 모듈
- tekton-piplines(tekton-pipelines-webhooks)
- ai-devops(cluster-local-gateway, katib-db-manager)
> Argocd-installer timezone 반영

- manifest/ai-devops/1.cluster-local-gateway.jsonnet
- manifest/ai-devops/6.katib.jsonnet
- manifest/argocd/templates/statefulset.yaml
- manifest/tekton-pipeline/tekton-pipeline.jsonnet
**ai-devops**
- cluster-local-gateway
- katib-db-manager
**argocd**
- argocd-application-controller
**tekton-pipline**
- tekton-pipelines-webhooks
> [mod] timezone 빠진 모듈 추가

- manifest/hyperregistry/templates/redis/statefulset.yaml
- manifest/hyperregistry/templates/trivy/trivy-sts.yaml
> [Hyperregistry] fix to set timezone for redis, trivy

- manifest/api-gateway/jwt-decode-auth/jwt-decode-auth-values.yaml
- manifest/api-gateway/jwt-decode-auth/values.yaml
- manifest/ceph-csi-cephfs/values.yaml
- manifest/ceph-csi-rbd/values.yaml
- manifest/service-binding-operator/service-binding-operator.yaml
- service binding, cephfs-csi, cephrbd-csi 수정
> Timezone error fix 

- application/helm/master-values.yaml
- application/helm/shared-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/ai-devops.yaml
- application/helm/templates/api-gateway-bootstrap.yaml
- application/helm/templates/efk.yaml
- application/helm/templates/grafana.yaml
- application/helm/templates/hypercloud.yaml
- application/helm/templates/jaeger.yaml
- application/helm/templates/kiali.yaml
- application/helm/templates/opensearch.yaml
- manifest/ai-devops/1.cluster-local-gateway.jsonnet
- manifest/ai-devops/6.katib.jsonnet
- manifest/api-gateway/gateway/charts/traefik/values.yaml
- manifest/api-gateway/gateway/templates/secrets.yaml
- manifest/tekton-pipeline/tekton-pipeline.jsonnet
- domain 변수 적용이 안되는 문제 처리
- master domain과 single domain을 분리  
- 이외의 에러처리
> Domain 작업 및 fix error 

- application/helm/templates/hyperregistry.yaml
- manifest/hypercloud/hypercloud-multi-operator.jsonnet
- manifest/hypercloud/hypercloud-multi-operator.yaml
multi-operator version: b5.0.26.13 => b5.0.31.1
> hyperregistry manifest error 수정 및 hypercloud multi-operator version upgrade

- application/helm/templates/gitlab.yaml
- [[IMS-285349](https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?issueId=285349&menuCode=issue_list)]
gitlab master 배포 추가
> gitlab master cluster 등록IMS-285349

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- manifest/helm-apiserver/helm-apiserver.jsonnet
> update helm apiserver version

- application/helm/master-values.yaml
- application/helm/shared-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/_helpers.tpl
- application/helm/templates/_template.tpl
- application/helm/templates/ai-devops.yaml
- application/helm/templates/api-gateway-bootstrap.yaml
- application/helm/templates/efk.yaml
- application/helm/templates/grafana-operator.yaml
- application/helm/templates/hyperauth.yaml
- application/helm/templates/hypercloud.yaml
- application/helm/templates/hyperregistry.yaml
- application/helm/templates/istio.yaml
- application/helm/templates/jaeger.yaml
- application/helm/templates/kiali.yaml
- application/helm/templates/opensearch.yaml
- docs/INSTALL_GUIDE_MASTER.md
- docs/INSTALL_MODULE_LIST.md
- manifest/ai-devops/9.notebook.jsonnet
- manifest/cluster-api-provider-aws/cluster-api-provider-aws.jsonnet
- manifest/grafana-operator/grafana-operator.jsonnet
- manifest/hypercloud/hypercloud-capi-aws-template.libsonnet
- manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
- manifest/hypercloud/hypercloud-multi-operator.jsonnet
- manifest/hypercloud/hypercloud-multi-operator.yaml
- manifest/tekton-pipeline/tekton-pipeline.yaml
- manifest/tekton-trigger/tekton-trigger.yaml
- grafana-operator에 들어가는 dns 수정
- istio sync시 retry 옵션 추가 
- capa credential guide 추가 및 예시 credential 변경
- [ims][290942] ingress api group을 모두 networking.k8s.io 로 변경
- [ims][289299]  hyperregistry externalURL 변경
- master-single을 위한 변수를 shared-values에 추가 
- hypercloud-multi-operator 5.0.34.2로 버전 업그레이드
> argocd-installer error 수정

- application/helm/master-values.yaml
- application/helm/shared-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/argocd.yaml
- manifest/api-gateway-bootstrap/templates/gateway.yaml
- manifest/argocd/values.yaml
- argocd ingress를 traefik ingress로 생성하도록 변경
- gitlab pvc 변수 추가 
- gateway 빠진 변수 추가
> error 수정 및 변수 추가 

- application/helm/templates/gitlab.yaml
- manifest/gitlab/templates/deployment.yaml
- manifest/gitlab/values.yaml
> add gitlab pvc

- [
- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/loki.yaml
- manifest/loki/loki-promtail.jsonnet
- fix loki manifest error
- gitlab pvc storage class 주석 추가
> fix loki manifest error + 주석 추가 

- application/helm/templates/gitlab.yaml
- manifest/hyperauth/hyperauth.jsonnet
- manifest/hypercloud/hypercloud-api-server.jsonnet
- 잘못된 gitlab externalURL 수정
- hyperauth version 1.1.2.1 업그레이드
- hypercloud api server 5.0.34.1 업그레이드
- 에러 처리
> version upgrade 및 error 처리

- manifest/cicd-operator/cicd-operator.jsonnet
[chore] update cicd-operator version to v0.4.13
- cicd-operator 0.4.3 -> 0.4.13
- cicd-blocker 0.4.3 -> 0.4.13
> [cicd-operator] update cicd-operator version to v0.4.13

- application/helm/templates/_template.tpl
- application/helm/templates/argocd.yaml
- manifest/gitlab/templates/deployment.yaml
- manifest/grafana-operator/grafana-operator-cert.yaml
- manifest/helm-apiserver/helm-apiserver.yaml
- certificate out of sync 에러 처리
- gitlab pvc out of sync 에러 처리
> argocd-installer error fix 

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- manifest/helm-apiserver/helm-apiserver.jsonnet
Version update 0.0.3 -> 0.0.4
- [fix] Init repo bug fix
> [helm-apiserver] image version update

- application/helm/master-values.yaml
- application/helm/shared-values.yaml
- application/helm/single-values.yaml
- manifest/api-gateway/console/console-values.yaml
- manifest/api-gateway/gateway/gateway-values-nodeport.yaml
- manifest/api-gateway/gateway/gateway-values.yaml
- manifest/api-gateway/jwt-decode-auth/jwt-decode-auth-values.yaml
- api-gateway-bootstrap regcred secret not found error로 해당 secret 사용하지 않도록 주석 처리
- single, master domain을 동일하게 변경
- argocd dex replicas를 0으로 변경
> argocd error 수정 및 요청 반영

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/argocd.yaml
- manifest/argocd/templates/deployment.yaml
- manifest/argocd/templates/networkpolicy.yaml
- manifest/argocd/templates/role.yaml
- manifest/argocd/templates/rolebinding.yaml
- manifest/argocd/templates/secret.yaml
- manifest/argocd/templates/service.yaml
- manifest/argocd/templates/serviceaccounts.yaml
- manifest/argocd/values.yaml
> argocd에서 dex 제거 

- manifest/gitlab/templates/deployment.yaml
[chore] edit gitlab manifest typo
- external_url 에러 수정
> [gitlab] edit gitlab manifest typo

- manifest/cicd-operator/gradle-build-task.yaml
- manifest/cicd-operator/maven-build-task.yaml
jar 빌드를 위한 sample Tekton task 추가
> [cicd-operator] add jar build Tekton task

- application/helm/templates/argocd.yaml
- application/helm/templates/service-binding-operator.yaml
- manifest/argocd/templates/namespace.yaml
- argocd 앱에서 namespace auto create 삭제 후, namespace manifest 추가했습니다 .
> argocd namespace 추가 

- manifest/gitlab/templates/deployment.yaml
> [fix] gitlab appsync error 

- manifest/redis-operator/redis-operator.jsonnet
redis 생성시 자동으로 만들어지는 그라파나 대시보드 정상화한 버전으로 업그레이드 하였습니다.
> [mod] redis operator 버전 업그레이드

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/gitlab.yaml
- manifest/gitlab/templates/deployment.yaml
- gitlab storageclass 사용에 대한 주석 추가
- gitlab default storage class 변수명 default로 변경
- hyperreigstry master cluster 사용으로 주석 변경
> gitlab storageclass 변수 변경 

- manifest/hypercloud/hypercloud-capi-aws-template.libsonnet
- manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
- manifest/hypercloud/hypercloud-multi-operator.jsonnet
> [feat] hypercloud-multi-operator version up:b5.0.34.5

- application/app_of_apps/single-applications.yaml
- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/aws-efs-csi-driver.yaml
- application/helm/templates/ceph-csi-cephfs.yaml
- application/helm/templates/ceph-csi-rbd.yaml
- manifest/aws-efs-csi-driver/.helmignore
- manifest/aws-efs-csi-driver/CHANGELOG.md
- manifest/aws-efs-csi-driver/Chart.yaml
- manifest/aws-efs-csi-driver/templates/NOTES.txt
- manifest/aws-efs-csi-driver/templates/_helpers.tpl
- manifest/aws-efs-csi-driver/templates/controller-deployment.yaml
- manifest/aws-efs-csi-driver/templates/controller-serviceaccount.yaml
- manifest/aws-efs-csi-driver/templates/csidriver.yaml
- manifest/aws-efs-csi-driver/templates/node-daemonset.yaml
- manifest/aws-efs-csi-driver/templates/node-serviceaccount.yaml
- manifest/aws-efs-csi-driver/templates/storageclass.yaml
- manifest/aws-efs-csi-driver/values.yaml
- manifest/ceph-csi-cephfs/templates/csiplugin-configmap.yaml
- manifest/ceph-csi-cephfs/templates/storageclass.yaml
- manifest/ceph-csi-cephfs/values.yaml
- manifest/ceph-csi-rbd/templates/csiplugin-configmap.yaml
- manifest/ceph-csi-rbd/templates/storageclass.yaml
- manifest/ceph-csi-rbd/values.yaml
- manifest/nfs-subdir-external-provisioner/values.yaml
- Add efs csi
- Add default storageclass setting
- Add ceph csi config setting
> [add] Add efs csi and storage setting

- application/helm/templates/aws-efs-csi-driver.yaml
- manifest/gitlab/templates/deployment.yaml
- [mod] fix aws-efs-csi-driver manifest error
- [mod] fix gitlab private registry image error
> fix argocd manifest error 

- manifest/cicd-operator/gradle-build-task.yaml
- manifest/cicd-operator/maven-build-task.yaml
IMS-290378
sample TektonTask에 git clone 수행하는 부분 추가.
> [cicd-operator] fix jar build sample TektonTask

- manifest/cicd-operator/cicd-operator.yaml
[chore] update cicd-operator version to v0.4.13
- add configmap
> [chore] update cicd-operator version to v0.4.13

- manifest/api-gateway/console/console-values.yaml
- manifest/api-gateway/console/values.yaml
console version 5.0.83.0 으로 변경
> update console version to 5.0.83.0

- manifest/api-gateway/console/Chart.yaml
- manifest/api-gateway/console/console-values.yaml
- manifest/api-gateway/console/values.yaml
console 버전 변경 5.0.82.3 -> 5.0.84.1
> console version to 5.0.84.1

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/nexus.yaml
- manifest/nexus/.helmignore
- manifest/nexus/Chart.yaml
- manifest/nexus/LICENSE
- manifest/nexus/README.md
- manifest/nexus/templates/NOTES.txt
- manifest/nexus/templates/_helpers.tpl
- manifest/nexus/templates/configmap-properties.yaml
- manifest/nexus/templates/configmap.yaml
- manifest/nexus/templates/deployment.yaml
- manifest/nexus/templates/ingress.yaml
- manifest/nexus/templates/namespace.yaml
- manifest/nexus/templates/pvc.yaml
- manifest/nexus/templates/secret.yaml
- manifest/nexus/templates/service.yaml
- manifest/nexus/templates/serviceaccount.yaml
- manifest/nexus/templates/test/test-check-logs.yaml
- manifest/nexus/templates/test/test-connection.yaml
- manifest/nexus/tests/deployment_test.yaml
- manifest/nexus/tests/ingress_test.yaml
- manifest/nexus/values.yaml
[넥서스 추가](https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?issueId=294099&menuCode=issue_list)
> add nexus (ims-294099)

- .github/template/root-applications.yaml
- .github/workflows/verify.yml
> [feat] git action flow update

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- manifest/sonarqube/.helmignore
- manifest/sonarqube/Chart.yaml
- manifest/sonarqube/templates/_helpers.tpl
- manifest/sonarqube/templates/namespace.yaml
- manifest/sonarqube/templates/service-account.yaml
- manifest/sonarqube/templates/sonarqube-conf-pvc.yaml
- manifest/sonarqube/templates/sonarqube-data-pvc.yaml
- manifest/sonarqube/templates/sonarqube-ingress.yaml
- manifest/sonarqube/templates/sonarqube-logs-pvc.yaml
- manifest/sonarqube/templates/sonarqube-service.yaml
- manifest/sonarqube/templates/sonarqube.yaml
- manifest/sonarqube/values.yaml
[ims-294098](https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?issueId=294098&menuCode=issue_list)
> add sonarqube

- manifest/cicd-operator/cicd-operator.jsonnet
- manifest/cicd-operator/cicd-operator.yaml
- manifest/tekton-pipeline/tekton-pipeline.yaml
- update CRD to v0.4.14 (integrationconfigs, integrationjobs)
- change tekton enable-custom-tasks value to true
[IMS] : 295059
> cicd-operator CRD version 0.4.14

- manifest/gitea/templates/_helpers.tpl
- manifest/gitea/values.yaml
- manifest/nexus/templates/ingress.yaml
- manifest/nexus/values.yaml
- manifest/tekton-pipeline/tekton-pipeline.yaml
[chore] add oauth default value
> gitea - add oauth default value

- manifest/gitea/values.yaml
- manifest/tekton-pipeline/tekton-pipeline.yaml
[chore] add oauth values example
> gitea - add oauth values example

- manifest/gitea/values.yaml
- manifest/nexus/templates/ingress.yaml
- manifest/nexus/values.yaml
- manifest/tekton-pipeline/tekton-pipeline.yaml
[chore] modify fullname, add subdomain
> Nexus - modify fullname, add subdomain

- manifest/sonarqube/templates/sonarqube-conf-pvc.yaml
- manifest/sonarqube/templates/sonarqube-data-pvc.yaml
- manifest/sonarqube/templates/sonarqube-ingress.yaml
- manifest/sonarqube/templates/sonarqube-logs-pvc.yaml
- manifest/sonarqube/values.yaml
- pvc 생성 에러 수정
- 버전업 9.8.0-community
> sonarqube - [fix] pvc 생성 에러 수정, 버전업 9.8.0-community

- manifest/calico/calico.jsonnet
calico log level 변수화 수정
- cni_network_config log level 문자열 변수화
- "BGPConfiguration 로그레벨 변수화
- "KubeControllersConfiguration" 로그레벨 변수화
- "FelixConfiguration" 로그레벨 변수화
> calico log level 변수화

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/cicd-operator.yaml
- manifest/cicd-operator/cicd-operator.jsonnet
> cicd-operator - log level 변수화

- manifest/hyperauth/kafka.jsonnet
- manifest/service-binding-operator/service-binding-operator.jsonnet
- manifest/service-binding-operator/service-binding-operator.yaml
1. hyperauth - kafka : resource request/limit 추가
2. service binding operator : image version 업데이트, resource request/limit 추가
> hyperauth-kafka / servicebinding template 최신화

- manifest/helm-apiserver/helm-apiserver.jsonnet
- Helm-apiserver resource 설정 추가
> Helm-apiserver resource 설정 추가

- manifest/image-validating-webhook/image-validating-webhook.jsonnet
> [Image-Validating-Webhook] set pod resources, loglevel

- manifest/hyperregistry/values.yaml
* 파드 리소스 설정
* 로그레벨 default 시 info 레벨로 변경
> [Hyperregistry] set pod resources, default loglevel

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/aws-efs-csi-driver.yaml
- application/helm/templates/ceph-csi-cephfs.yaml
- application/helm/templates/ceph-csi-rbd.yaml
- application/helm/templates/nfs-subdir-external-provisioner.yaml
- manifest/nfs-subdir-external-provisioner/templates/deployment.yaml
- manifest/nfs-subdir-external-provisioner/values.yaml
- Add log level to efs,nfs,ceph csi module
> [mod] Add log level to storge module

- application/helm/templates/istio-1-15-4.yaml
- manifest/istio/istio-istiod/values.yaml
- manifest/istio/namespace/namespaces.yaml
5.2 버전으로 적용되서 namespace가 생성이 안됐습니다.
istio-system 네임스페이스 생성하게 수정하였습니다. 
풀리퀘 수락 부탁드립니다.
> fix : namespaces.yaml 파일 추가

- manifest/istio/istio-gateway/templates/job.yaml
bitnami/kubectl 이미지 버전 1.25.5로 변경
> Update the job.yaml to use image version 1.25.5

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- manifest/template-service-broker/tsb-deployment.jsonnet
- template service broker 로그 레벨 info 로 변경
- deployment container pod limit 설정
> [mod] tsb pod limit & loglevel to info

- manifest/api-gateway/console/values.yaml
- manifest/api-gateway/gateway/charts/traefik/values.yaml
- manifest/api-gateway/jwt-decode-auth/values.yaml
- manifest/api-gateway/oauth2-proxy/values.yaml
- manifest/cert-manager/values.yaml
[ims][295607] api-gateway, cert-manager resources 설정
> [ims][295607] api-gateway, cert-manager resources 설정

- manifest/api-gateway/cert-manager/values.yaml
- manifest/api-gateway/console/values.yaml
- manifest/api-gateway/gateway/charts/traefik/values.yaml
- manifest/api-gateway/jwt-decode-auth/values.yaml
[ims][295607] api-gateway, cert-manager resources 설정 v5.1.0
> [ims][295607] api-gateway, cert-manager resources 설정 v5.1.0

- manifest/api-gateway/cert-manager/values.yaml
- manifest/api-gateway/console/values.yaml
- manifest/api-gateway/gateway/charts/traefik/values.yaml
- manifest/api-gateway/jwt-decode-auth/values.yaml
[ims][295607] api-gateway, cert-manager resources 설정 v.5.1.1
> [ims][295607] api-gateway, cert-manager resources 설정 v.5.1.1

- application/helm/templates/gitea.yaml
- manifest/gitea/values.yaml
> gitea - keycloak client 초기 설정

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/argocd.yaml
- manifest/argocd/templates/deployment.yaml
- manifest/argocd/templates/statefulset.yaml
- manifest/argocd/values.yaml
- argocd 컴포넌트 log level 변수화
- 리소스 제한 적용
> [Argocd] 로그 레벨 변수화 및 리소스 제한 적용

- manifest/hypercloud/hypercloud-capi-aws-template.libsonnet
- manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
- manifest/hypercloud/hypercloud-capi-vsphere-upgrade-template.libsonnet
- manifest/hypercloud/hypercloud-multi-operator.jsonnet
- manifest/hypercloud/hypercloud-multi-operator.yaml
- hypercloud multi-operator version up v5.1.1.0
- capi version 호환을 위한 cluster template 업데이트
> [feat] hypercloud multi-operator 5.1.1.0 version update

- manifest/gitea/values.yaml
- manifest/sonarqube/templates/sonarqube-conf-pvc.yaml
- manifest/sonarqube/templates/sonarqube-data-pvc.yaml
- manifest/sonarqube/templates/sonarqube-ingress.yaml
- manifest/sonarqube/templates/sonarqube-logs-pvc.yaml
- manifest/sonarqube/values.yaml
[IMS 294945]
- [chore] selfsigned CA settings
> gitea - selfsigned CA settings

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- manifest/loki/README.md
master-values.yaml 및 single-values.yaml에 log-level 설정 관련 description 추가
> [mod] Opensearch, Loki loglevel 설정 description 추가

- manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
- manifest/hypercloud/hypercloud-multi-operator.jsonnet
- multi-operator image version 수정
- vsphere-csi-controller error 수정
> [etc] multi-operator image version 수정 및 vsphere-csi-controller error 수정

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/service-binding-operator.yaml
- manifest/service-binding-operator/service-binding-operator.jsonnet
1. master_value.yaml / single_value.yaml 
2. service-binding-operator.jsonnet
3. service-binding-operator.yaml
> mod: service-binding log_level 조절 가능하도록 parameter화

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- manifest/hyperauth/kafka.jsonnet
- manifest/strimzi-kafka-cluster-operator/kafka-crd-key-mapping.yaml
- manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.jsonnet
- manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.yaml
strimzi kafka operator 0.32.0 버전 업그레이드
> [feat] strimzi kafka operator 0.32.0 버전 업그레이드

- application/helm/templates/api-gateway-oauth2-proxy.yaml
- manifest/api-gateway/jwt-decode-auth/values.yaml
- manifest/api-gateway/oauth2-proxy/Chart.yaml
- manifest/api-gateway/oauth2-proxy/values.yaml
- 강제로 동기화 못하게 selfHeal: false로 번경 
- oauth2-proxy image 7.3.1로 변경
> IMS 298144 관련 이슈 처리반영

- manifest/gitea/values.yaml
update gitea version to 1.18.0
> gitea - k8s 1.25v manifest 반영

- manifest/tekton-pipeline/tekton-pipeline.yaml
- custom task 실행 에러 문제 해결을 위한 flags 값 변경
> tekton-pipeline - set feature-flags

- manifest/catalog-controller/catalog-controller.jsonnet
> [mod] change broker relist interval

- manifest/api-gateway/console/Chart.yaml
- manifest/api-gateway/console/console-values.yaml
- manifest/api-gateway/console/values.yaml
ims#[298069](https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?issueId=298069) console ai-devops 메뉴 핫픽스로 인해 버전 수정
> [ims][298069] console ai-devops 메뉴 핫픽스

- manifest/service-binding-operator/service-binding-operator.jsonnet
service-binding-operator - simple image tag로 변경
> change service-binding-operator image as simple tag

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- manifest/gitea/charts/memcached/values.yaml
- manifest/gitea/values.yaml
- value.yaml
- config.webhook: ALLOWED_HOST_LIST: '*'
(IMS 296831: 웹훅 등록을 위한 ALLOWED_HOST_LIST 설정)
- resource.limits 스케일링
(특정 동작 시 메모리 부족 현상이 나타나 cpu 및 메모리 스케일링)
- admin config 수정
(어드민 계정 접속정보 수정, root/password)
- loglevel 범위 주석 추가
- nfs StorageClass에서 권한 문제로 인해 DBMS postgreSQL 에서 mariaDB로 변경
> Gitea - bug fix

- manifest/gitea/charts/mariadb/values.yaml
- manifest/gitea/charts/memcached/values.yaml
- modify memcached, mariaDB pod resources
> Gitea - modify memcached, mariaDB pod resources

- manifest/cert-manager/values.yaml
[ims][298489] OOM killeld 이슈 해결
cainjector의 limit.memory를 128Mi에서 512Mi로 증가
> [ims][298489] OOM killeld 이슈 해결

- application/helm/single-values.yaml
- manifest/argocd/values.yaml
- Add ArgoCD redis image repo url
- redis => docker.io/library/redis
> Add argocd redis image repo URL

- manifest/hyperauth/kafka.jsonnet
[mod] hyperauth kafka exporter 리소스 설정 추가
> [mod] hyperauth kafka exporter 리소스 설정 추가

- manifest/gitea/charts/mariadb/values.yaml
- manifest/gitea/charts/memcached/values.yaml
- manifest/gitea/values.yaml
- pod resources
- enable mariaDB
- modify admin config
> Gitea - bug fix (release-v5.1.1)

- manifest/gitea/charts/mariadb/values.yaml
- manifest/gitea/charts/memcached/values.yaml
- manifest/gitea/values.yaml
- pod resources
- enable mariaDB
- modify admin config
> Gitea - bug fix (release-v5.1.0)

- manifest/service-mesh/jaeger/7.jaeger.jsonnet
add resources limits and requests: 5.1.1
> jaeger add resources limits and requests: 5.1.1

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/nfs-subdir-external-provisioner.yaml
- manifest/nfs-subdir-external-provisioner/templates/deployment.yaml
- manifest/nfs-subdir-external-provisioner/values.yaml
nfs-provisioner에  resource 설정 (cpu,memory) 추가
nfs-provisioner에 error log level 지원 추가
- log level 0-5 (info-debug) 에서 0-6 으로 변경(0:error, 1:info, 6:debug)
> [mod] [nfs] Add resource setting, error log level

- manifest/service-mesh/jaeger/7.jaeger.jsonnet
add resources limits and requests in 5.1.0
> jaeger add resources limits and requests: 5.1.0

- manifest/service-mesh/jaeger/7.jaeger.jsonnet
Jaeger add resources limits and requests
> jaeger add resources limits and requests: main

- manifest/gitlab/templates/deployment.yaml
- manifest/gitlab/values.yaml
> Gitlab - version up to 15.3.2 (release-v5.1.0)

- manifest/gitlab/templates/deployment.yaml
- manifest/gitlab/values.yaml
> Gitlab - version up to 15.3.2 (release-v5.1.1)

- application/helm/templates/gitea.yaml
> Gitea - fix typo

- manifest/api-gateway/gateway/Chart.yaml
- manifest/api-gateway/gateway/templates/middleware.yaml
accessAllowOrigin에 https:// 부분 추가 (오승주 연구원님과 확인)
> bugfix: cors origin 버그 수정

- manifest/gitea/templates/_helpers.tpl
- manifest/gitea/templates/gitea/init.yaml
- gitea 파드 재실행 시 oidc 인증 오류 수정
> Gitea - oidc 버그 수정

- manifest/gitlab/templates/deployment.yaml
> Gitlab - puma worker_processes 최적화 (release5.1.0)

- manifest/gitlab/templates/deployment.yaml
> Gitlab - puma worker_processes 최적화 (release5.1.1)

- .github/template/root-applications.yaml
- manifest/cluster-api/templates/capi-aws/etc.yaml
- manifest/cluster-api/templates/capi-vsphere/etc.yaml
- manifest/cluster-api/templates/capi/etc.yaml
https://ims.tmaxsoft.com/tody/ims/issue/issueView.do?currentSystem=ims&issueId=299815
> [IMS] [5.0] CAPI 앱카드 내 crd, c-role OutOfSync 이슈

- manifest/service-mesh/istio/2.istio-base.yaml
istio: add key-mapping for crds v5.1.0
> istio: add key-mapping for crds v5.1.0

- manifest/api-gateway/jwt-decode-auth/templates/monitoring-ingressroute.yaml
traefik을 통한 k8s API 호출이 jwt 검증하도록 middleware 추가
> traefik을 통한 k8s API 호출이 jwt 검증하도록 middleware 추가

- application/helm/templates/api-gateway-gateway.yaml
- manifest/api-gateway/gateway/templates/configmap-static.yaml
- manifest/api-gateway/gateway/templates/middleware.yaml
master일때만 accessControlAllowOriginList 사용하도록 분기 처리
> master일때만 accessControlAllowOriginList 사용하도록 분기 처리

- manifest/opensearch/opensearch-fluentd.jsonnet
기존 설정: tmaxcloud@file
변경 후 설정: insecure@file
> [mod] opensearch-dashboards traefik annotation 수정

- manifest/api-gateway-bootstrap/templates/gateway.yaml
- manifest/api-gateway/gateway/templates/pre-install.yaml
- manifest/api-gateway/gateway/values.yaml
[ims][300090] .Values.cluster 변수 에러 수정
> [ims][300090] .Values.cluster 변수 에러 수정

- application/helm/templates/api-gateway-gateway.yaml
- manifest/api-gateway/gateway/templates/configmap-static.yaml
- manifest/api-gateway/gateway/templates/middleware.yaml
- manifest/api-gateway/gateway/values.yaml
gateway values.yaml에 global 변수 추가
> gateway values.yaml에 global 변수 추가

- manifest/api-gateway/console/templates/cmp-default-menus-sample.yaml
[IMS 300293][5.1.1] ai-devops 메뉴의 CMP 반영 요청
> [IMS 300293][5.1.1] ai-devops 메뉴의 CMP 반영 요청

- manifest/catalog-controller/catalog-controller.yaml
- manifest/template-service-broker/template-service-broker.yaml
- change crd version from v1beta1 to v1
> 서비스 카탈로그 CRD version update (v1beta1 -> v1)

- manifest/istio/istio-base/crds/crd-all.gen.yaml
- manifest/service-mesh/istio/2.istio-base.yaml
> istio: CRD converting v5.1.1

- manifest/hypercloud/templates/hypercloud-api-server/version-config.yaml
[ims][300551] version-config의 traefik 컨테이너 이름 수정
> [ims][300551] version-config의 traefik 컨테이너 이름 수정

- manifest/hypercloud/templates/hypercloud-api-server/version-config.yaml
[ims][300551] version-config traefik 컨테이너 이름 재수정
> [ims][300551] version-config traefik 컨테이너 이름 재수정

- manifest/argocd/templates/configmap.yaml
- argocd App Card의 Out of Sync 이슈 해결을 위하여 configmap에 ignoreAggregatedRole 옵션 추가
> Modify Argocd-cm

- manifest/argocd/templates/configmap.yaml
- argocd App Card의 Out of Sync 이슈 해결을 위하여 configmap에 ignoreAggregatedRole 옵션 추가
> Modify Argocd configmap

- manifest/hyperauth/hyperauth_certs.yaml
[mod] Hyperauth cert-manager apiVersion 업그레이드
v1alpha2 → v1 변경사항 반영
> [mod] Hyperauth cert-manager apiVersion 업그레이드

- manifest/catalog-controller/catalog-controller.jsonnet
- manifest/catalog-controller/catalog-controller.yaml
- update mutating/validating webhook configuration apiversion 
v1beta1 -> v1
> [catalog-controller] update webhook apiversion

- manifest/tekton-pipeline/tekton-pipeline.jsonnet
- manifest/tekton-pipeline/tekton-pipeline.yaml
- manifest/tekton-trigger/tekton-trigger-interceptors.yaml
- manifest/tekton-trigger/tekton-trigger.jsonnet
- manifest/tekton-trigger/tekton-trigger.yaml
- [chore] version up tekton-pipeline to v0.43.0, tekton-trigger to v0.22.0
> [chore] version up tekton-pipeline to v0.43.0, tekton-trigger to v0.22.0

- application/helm/templates/cicd-operator.yaml
- manifest/cicd-operator/cicd-operator.jsonnet
- manifest/cicd-operator/cicd-operator.yaml
- manifest/cicd-operator/gradle-build-task.yaml
- manifest/cicd-operator/maven-build-task.yaml
- manifest/tekton-pipeline/tekton-pipeline.jsonnet
- manifest/tekton-pipeline/tekton-pipeline.yaml
- manifest/tekton-trigger/tekton-trigger-interceptors.yaml
- manifest/tekton-trigger/tekton-trigger.jsonnet
- manifest/tekton-trigger/tekton-trigger.yaml
- [chore] version up cicd-operator to v0.6.2
> [chore] version up cicd-operator to v0.6.2

- application/helm/templates/gitea.yaml
- manifest/gitea/charts/mariadb/charts/common/templates/_images.tpl
- manifest/gitea/charts/mariadb/values.yaml
- manifest/gitea/charts/memcached/charts/common/templates/_images.tpl
- manifest/gitea/charts/memcached/values.yaml
- manifest/gitea/values.yaml
Gitea - private registry 설정 추가
> Gitea - private registry 설정 추가(v5.2)

- application/helm/templates/gitea.yaml
- manifest/gitea/charts/mariadb/charts/common/templates/_images.tpl
- manifest/gitea/charts/mariadb/values.yaml
- manifest/gitea/charts/memcached/charts/common/templates/_images.tpl
- manifest/gitea/charts/memcached/values.yaml
- manifest/gitea/values.yaml
Gitea - private registry 설정 추가
> Gitea - private registry 설정 추가(v5.1.1)

- manifest/gitea/charts/mariadb/charts/common/templates/_images.tpl
- manifest/gitea/charts/memcached/charts/common/templates/_images.tpl
> [fix] gitea registry bug fix

- manifest/hypercloud/templates/hypercloud-multi-operator/capi-vsphere-template.yaml
- manifest/hypercloud/templates/hypercloud-multi-operator/crd.yaml
- manifest/hypercloud/templates/hypercloud-multi-operator/etc.yaml
- manifest/hypercloud/values.yaml
- service instance 사용에서 template instance 사용으로 변경 
- instance ready check logic 변경
> [feat] multi-operator 5.1.3.1 update

- application/helm/templates/cicd-operator.yaml
- manifest/cicd-operator/cicd-operator.jsonnet
- manifest/cicd-operator/cicd-operator.yaml
- manifest/cicd-operator/gradle-build-task.yaml
- manifest/cicd-operator/maven-build-task.yaml
cicd-operator version up to v0.6.2
> cicd-operator version up to v0.6.2 (release-v5.1.1)

- manifest/argocd/templates/configmap.yaml
- Argocd cm에 ignoreAggregatedRoles options 추가
> Add ignoreAggregatedRoles options in argocd cm

- manifest/cicd-operator/cicd-operator.yaml
- manifest/cicd-operator/gradle-build-task.yaml
- manifest/cicd-operator/maven-build-task.yaml
- [fix] k8s 1.21 버전에서 설치 시 발생 오류 해결
> [fix] k8s 1.21 버전에서 설치 시 발생 오류 해결

- application/helm/templates/istio-1-15-4.yaml
- manifest/istio-bootstrap/.helmignore
- manifest/istio-bootstrap/Chart.yaml
- manifest/istio-bootstrap/templates/istio-base.yaml
- manifest/istio-bootstrap/templates/istio-gateway.yaml
- manifest/istio-bootstrap/templates/istio-istiod.yaml
- manifest/istio-bootstrap/templates/istio-namespace.yaml
- manifest/istio-bootstrap/values.yaml
> feat: add istio bootstrap v5.1.1

- manifest/gitlab/templates/deployment.yaml
- manifest/gitlab/values.yaml
- [chore] upgrade gitlab version to 15.3.2-ce.0
> [chore] upgrade gitlab version to 15.3.2-ce.0

- manifest/cicd-operator/cicd-operator.yaml
- [mod] cicd-operator key-mapping
> [mod] cicd-operator key-mapping

- manifest/cicd-operator/cicd-operator.yaml
- manifest/cicd-operator/gradle-build-task.yaml
- manifest/cicd-operator/maven-build-task.yaml
- [mod] cicd-operator key-mapping
- [fix] build-task 설치 에러
> [mod] cicd-operator key-mapping v5.1.1

- manifest/template-service-broker/template-service-broker.yaml
- Template operator CRD key-mapping 반영
> Add description key in tsb CRDs

- manifest/gitea/values.yaml
[fix] gitea set SKIP_TLS_VERIFY param true
> [fix] gitea set SKIP_TLS_VERIFY param true

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/kiali.yaml
- manifest/service-mesh/kiali/8.kilai.jsonnet
update kiali version to 1.59.0 in v5.1.1
> apply kiali v1.59.0 in v5.1.1

- manifest/api-gateway/oauth2-proxy/values.yaml
[ims][303684] oauth2-proxy가 사용하는 redis의 resource request/limit 설정
> [ims][303684] oauth2-proxy가 사용하는 redis의 resource request/limit 설정

- manifest/tekton-pipeline/tekton-pipeline.yaml
- manifest/tekton-trigger/tekton-trigger.yaml
[fix] tekton shared resource warning
> [fix] tekton shared resource warning

- manifest/nexus/values.yaml
[fix] nexus image registry value
> [fix] nexus image registry value

- manifest/sonarqube/values.yaml
> [fix] sonarqube busybox repo

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/gitea.yaml
- manifest/gitea/templates/gitea/init.yaml
- manifest/gitea/values.yaml
[fix] add gitea oauth enabled opt
> [fix] add gitea oauth enabled opt

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/gitea.yaml
- manifest/gitea/templates/gitea/init.yaml
- manifest/gitea/values.yaml
- manifest/tekton-trigger/tekton-trigger.yaml
[fix] add gitea oauth enabled opt
[fix] tekton-trigger ClusterRole
> [fix] add gitea oauth enabled opt, tekton-trigger ClusterRole

- manifest/tekton-pipeline/tekton-pipeline.jsonnet
tekton controller 실행 시 shell-image-win 옵션 제거
> tekton-pipeline/delete shell-image-win args

- manifest/gitea/charts/mariadb/values.yaml
- manifest/gitea/charts/memcached/values.yaml
- manifest/gitea/templates/_helpers.tpl
- manifest/gitea/templates/gitea/ingress.yaml
- manifest/gitea/values.yaml
[IMS-298330] argocd application name으로 인한 service HOST_NAME 변경을 방지하기 위해 리소스 네임 고정
> [fix] fullnameOverride

- application/helm/templates/argocd.yaml
- manifest/argocd/templates/configmap.yaml
- manifest/argocd/templates/secret.yaml
- manifest/argocd/values.yaml
- manifest/argorollout/values.yaml
> [argocd] feat: oidc automation in hc-5.2

- manifest/image-validating-webhook/image-validating-webhook.yaml
hc-5.2에 추가, 변경, 제거되는 네임스페이스에 대해 이미지 벨리데이션 웹훅의 화이트리스트 업데이트
> [image-validation-webhook] mod: update whitelist for hc-5.2

- manifest/hypercloud/templates/hypercloud-multi-operator/capi-aws-template.yaml
- manifest/hypercloud/templates/hypercloud-multi-operator/capi-vsphere-template.yaml
- manifest/hypercloud/templates/hypercloud-multi-operator/crd.yaml
update calico version 3.16 to 3.24
> update calico version in capi vsphere, aws template.yaml

- application/helm/master-values.yaml
- application/helm/single-values.yaml
- application/helm/templates/nexus.yaml
- application/helm/templates/sonarqube.yaml
[fix] add subdomain to nexus, sonarqube
> [fix] add subdomain to nexus, sonarqube

- application/helm/templates/nexus.yaml
- manifest/nexus/templates/deployment.yaml
- manifest/nexus/values.yaml
nexus 모듈에 loglevel 적용 안되는 사항 수정
> [fix] nexus loglevel

- manifest/nexus/templates/deployment.yaml
- manifest/nexus/values.yaml
- [ims-313872] nexus 폐쇠망 이미지레지스트리 설정
> [fix] nexus 폐쇠망 이미지레지스트리 설정

- manifest/tekton-pipeline/tekton-pipeline.yaml
- tekton-pipelines 네임스페이스의 pod-security 변경
> [fix] tekton pod-security

- application/helm/templates/sonarqube.yaml
- manifest/gitea/templates/gitea/ingress.yaml
- manifest/nexus/templates/ingress.yaml
- manifest/sonarqube/values.yaml
- sonarqube issuerurl 수정
- gitea, nexus ingress의 annotation 수정
> [fix] sonarqube issuerurl 수정, annotation 수정

- manifest/hyperauth/initialization.yaml
> [mod] add gitea/sonarqube as default client

- manifest/cicd-operator/cicd-operator.jsonnet
- [chore] cicd-operator version up to v0.6.4
> [chore] cicd-operator version up to v0.6.4
